AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for MDEP Staging VPC"
Parameters:
  DefaultVpcId:
    Description: "Default VPC ID"
    Type: String
Resources:
  SmdhVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MDEP-Staging-VPC

  SmdhElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  SmdhElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  SmdhElasticIP3:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  SmdhInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MDEP-Staging-InternetGateway

  SmdhVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: SmdhVPC
      InternetGatewayId:
        Ref: SmdhInternetGateway

  SmdhPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: 
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-Subnet-Private-1

  SmdhPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-Subnet-Private-2

  SmdhPrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
        - 2
        - Fn::GetAZs:
            Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-Subnet-Private-3


  SmdhPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicSubnet1
  
  SmdhPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.5.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicSubnet2
  
  SmdhPublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: SmdhVPC
      CidrBlock: 10.0.6.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicSubnet3

  SmdhNATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
          - SmdhElasticIP1
          - AllocationId
      SubnetId:
        Ref: SmdhPublicSubnet1
  
  SmdhNATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
          - SmdhElasticIP2
          - AllocationId
      SubnetId:
        Ref: SmdhPublicSubnet2
  
  SmdhNATGateway3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
          - SmdhElasticIP3
          - AllocationId
      SubnetId:
        Ref: SmdhPublicSubnet3

  SmdhPublicRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicRouteTable1
  
  SmdhPublicRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicRouteTable2

  SmdhPublicRouteTable3:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PublicRouteTable3

  SmdhPublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SmdhPublicSubnet1
      RouteTableId:
        Ref: SmdhPublicRouteTable1

  SmdhPublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SmdhPublicSubnet2
      RouteTableId:
        Ref: SmdhPublicRouteTable2

  SmdhPublicSubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SmdhPublicSubnet3
      RouteTableId:
        Ref: SmdhPublicRouteTable3

  SmdhPublicRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPublicRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SmdhInternetGateway
  
  SmdhPublicRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPublicRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SmdhInternetGateway
  
  SmdhPublicRoute3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPublicRouteTable3
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SmdhInternetGateway

  SmdhPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PrivateRouteTable1
  
  SmdhPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PrivateRouteTable2
  
  SmdhPrivateRouteTable3:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SmdhVPC
      Tags:
        - Key: Name
          Value: MDEP-Staging-PrivateRouteTable3

  SmdhPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SmdhNATGateway1

  SmdhPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SmdhNATGateway2

  SmdhPrivateRoute3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SmdhPrivateRouteTable3
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SmdhNATGateway3

  SmdhPrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Ref: SmdhPrivateSubnet1
      RouteTableId:
        Ref: SmdhPrivateRouteTable1

  SmdhPrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SmdhPrivateSubnet2
      RouteTableId:
        Ref: SmdhPrivateRouteTable2

  SmdhPrivateSubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Ref: SmdhPrivateSubnet3
      RouteTableId:
        Ref: SmdhPrivateRouteTable3

  SmdhVPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECR + DockerHub VPC Endpoint
      VpcId:
        Ref: SmdhVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.1.0/24
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.2.0/24
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: MDEP-Staging-VPCEndpointSecurityGroup

  SmdhECRVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: 
        Fn::Sub: com.amazonaws.${AWS::Region}.ecr.dkr
      VpcId:
        Ref: SmdhVPC
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - Ref: SmdhVPCEndpointSecurityGroup
      SubnetIds: 
        - Ref: SmdhPrivateSubnet1
        - Ref: SmdhPrivateSubnet2
        - Ref: SmdhPrivateSubnet3
      VpcEndpointType: Interface

  SmdhVpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerVpcId:
        Ref: DefaultVpcId
      VpcId:
        Ref: SmdhVPC
      PeerRegion: 
        Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MDEP-Staging-VpcPeeringConnection  

  RouteToPeeredVPC1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: 
        Ref: SmdhPrivateRouteTable1
      DestinationCidrBlock: 172.31.0.0/16
      VpcPeeringConnectionId: 
        Ref: SmdhVpcPeeringConnection

  RouteToPeeredVPC2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: 
        Ref: SmdhPrivateRouteTable2
      DestinationCidrBlock: 172.31.0.0/16
      VpcPeeringConnectionId: 
        Ref: SmdhVpcPeeringConnection

  RouteToPeeredVPC3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: 
        Ref: SmdhPrivateRouteTable3
      DestinationCidrBlock: 172.31.0.0/16
      VpcPeeringConnectionId: 
        Ref: SmdhVpcPeeringConnection

Outputs:
  VpcId:
    Description: The ID of the VPC created
    Value: 
      Ref: SmdhVPC
    Export:
      Name: Smdh-Staging-VPC-Id
  PrivateSubnet1Id:
    Description: The ID of the first private subnet
    Value:
      Ref: SmdhPrivateSubnet1
    Export:
      Name: Smdh-Staging-Private-Subnet1-Id
  PrivateSubnet2Id:
    Description: The ID of the second private subnet
    Value:
      Ref: SmdhPrivateSubnet2
    Export:
      Name: Smdh-Staging-Private-Subnet2-Id
  PrivateSubnet3Id:
    Description: The ID of the third private subnet
    Value:
      Ref: SmdhPrivateSubnet3
    Export:
      Name: Smdh-Staging-Private-Subnet3-Id
  PublicSubnet1Id:
    Description: The ID of the first public subnet
    Value:
      Ref: SmdhPublicSubnet1
    Export:
      Name: Smdh-Staging-Public-Subnet1-Id
  PublicSubnet2Id:
    Description: The ID of the second public subnet
    Value:
      Ref: SmdhPublicSubnet2
    Export:
      Name: Smdh-Staging-Public-Subnet2-Id
  PublicSubnet3Id:
    Description: The ID of the third public subnet
    Value:
      Ref: SmdhPublicSubnet3
    Export:
      Name: Smdh-Staging-Public-Subnet3-Id