x-aws-loadbalancer: "MDEP-Staging-ALB"
x-aws-cloudformation:
  Resources:
    CkanTCP80Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: CkanTCP80TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "${CERT_ARN}"
        Protocol: HTTPS
        Port: 443
      Type: AWS::ElasticLoadBalancingV2::Listener
    # compose ecs integration doesn't handle 0 min percent for update config.
    CkanworkerService:
      Properties:
        DeploymentConfiguration:
          MaximumPercent: 100
          MinimumHealthyPercent: 0

services:
  ckan:
    x-aws-role: &ckan-role
      Version: "2012-10-17"
      Statement:
        - Sid: S3BucketAccess
          Effect: Allow
          Action:
            - s3:*
            - s3-object-lambda:*
          Resource:
            - arn:aws:s3:::${CKAN_SMDH__AWS_STORAGE_BUCKET_NAME}/*
        - Sid: DataSciSharingIAMAccess
          Effect: Allow
          Action:
            - iam:ListPolicies
            - iam:ListRoles
            - iam:ListUsers
            - iam:ListGroups
          Resource: "*"
        - Sid: DataSciSharingIAMManagedResourcesActions
          Effect: Allow
          Action: [iam:*]
          Resource:
            - Fn::Join: [":", ["arn:aws:iam:", Ref: "AWS::AccountId", "policy/ckan-smdh/datasci-sharing/*"]]
            - Fn::Join: [":", ["arn:aws:iam:", Ref: "AWS::AccountId", "group/ckan-smdh/datasci-sharing/*"]]
        - Sid: SQSResourceManagement
          Effect: Allow
          Action: [sqs:*]
          Resource:
            Fn::Join: [":", [
                "arn:aws:sqs:${CKANEXT__CLOUDSTORAGE__SYNC__QUEUE_REGION}",
                Ref: "AWS::AccountId",
                "${CKANEXT__CLOUDSTORAGE__SYNC__QUEUE_NAME}",
              ]]

  ckan-worker:
    x-aws-role: *ckan-role
