x-aws-vpc: ${NEW_VPC_ID}
x-aws-cloudformation:
  Resources:
    CkanService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED

    DatapusherService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED

    RedisService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED

    SolrService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED

    CkanTCP80Listener:
      Properties:
        Certificates:
          - CertificateArn: "${CERT_ARN}"
        Protocol: HTTPS
        Port: 443
      Type: AWS::ElasticLoadBalancingV2::Listener
  
