version: "3.8"

volumes:
  ckan_storage:
    driver_opts:
      uid: 0
      gid: 0
  pg_data:
    driver_opts:
      uid: 0
      gid: 0
  solr_data:
    driver_opts:
      uid: 0
      gid: 0

x-aws-loadbalancer: "MDEP-Staging-ALB"
x-aws-cloudformation:
  Resources:
    NginxTCP80Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: NginxTCP80TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "${CERT_ARN}"
        Protocol: HTTPS
        Port: 443
      Type: AWS::ElasticLoadBalancingV2::Listener

services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: ${INTERNAL_REG}/mdepckan/ckan-nginx:latest
    deploy:
      resources:
         limits:
           cpus: '2'
           memory: 8GB
#       x-aws-autoscaling:
#         min: 1
#         max: 3
#         cpu: 75
    depends_on:
      ckan:
        condition: service_healthy
    networks:
      - ckan-internal
    ports:
      - "${NGINX_PORT_HOST}:${NGINX_PORT}"


  ckan:
    container_name: ${CKAN_CONTAINER_NAME}
    image: ${INTERNAL_REG}/mdepckan/ckan-deploy:latest
    deploy:
      resources:
          limits:
            cpus: '2'
            memory: 16GB
#       x-aws-autoscaling:
#         min: 1
#         max: 3
#         cpu: 75
    env_file:
      - .env
    networks:
      - ckan-internal
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - ckan_storage:/var/lib/ckan
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "-qO", "/dev/null", "${CKAN_SITE_URL}"]
    
  datapusher:
    container_name: ${DATAPUSHER_CONTAINER_NAME}
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${CKAN_DATAPUSHER_URL}"]
    networks:
      - ckan-internal

  db:
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    image: ${INTERNAL_REG}/mdepckan/ckan-postgresql:latest
    deploy:
      resources:
          limits:
            cpus: '2'
            memory: 8GB
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]
    networks:
      - ckan-internal
     
  solr:
    container_name: ${SOLR_CONTAINER_NAME}
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    networks:
      - ckan-internal
    # restart: unless-stopped
    volumes:
      - solr_data:/var/solr
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
    networks:
      - ckan-internal

networks:
    ckan-internal:
