x-aws-loadbalancer: "MDEP-Staging-ALB"
x-aws-cloudformation:
  Resources:
    Ckan5000Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: Ckan5000TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "${CERT_ARN}"
        Protocol: HTTPS
        Port: 443
      Type: AWS::ElasticLoadBalancingV2::Listener
    # create our own LB side security group for the ckan_internal network
    # which we attach to the ALB (manually) - all this will be done automatically in the future with udpates to compose-cli hopefully
    # see https://github.com/docker/compose-cli/pull/2215
    CkanLB5000Ingress:
      Properties:
        CidrIp: 0.0.0.0/0
        Description: 5000/tcp on CkanLB
        FromPort: 5000
        GroupId:
          Ref: CkanLB
        IpProtocol: TCP
        ToPort: 5000
      Type: AWS::EC2::SecurityGroupIngress
    CkanLB:
      Properties:
        GroupDescription: Security group for ckan-LB comm
        Tags:
          - Key: com.docker.compose.project
            Value: docker-ckan
          - Key: com.docker.compose.network
            Value: docker-ckan_ckan-internal
      Type: AWS::EC2::SecurityGroup
 
