x-aws-loadbalancer: "MDEP-Staging-ALB"
x-aws-cloudformation:
  Resources:
    Ckan5000Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: Ckan5000TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "${CERT_ARN}"
        Protocol: HTTPS
        Port: 443
      Type: AWS::ElasticLoadBalancingV2::Listener
    Ckaninternal5000Ingress:
      Properties:
        FromPort: 5000
        ToPort: 5000
        Description: LB side comm with ckan:5000
        GroupId:
          Ref: CkaninternalNetwork
        IpProtocol: TCP
        SourceSecurityGroupId:
          Ref: CkanLB
      Type: AWS::EC2::SecurityGroupIngress
    # create our own LB side security group for the ckan_internal network
    # which we attach to the ALB
    CkanLB:
      Properties:
        GroupDescription: Security group for ckan-LB comm
        Tags:
          - Key: com.docker.compose.project
            Value: docker-ckan
          - Key: com.docker.compose.network
            Value: docker-ckan_ckan-internal
      Type: AWS::EC2::SecurityGroup