name: Deploy CKAN image

on:
   workflow_run:
   # only runs additional steps if [ Create Ckan Base image ] was successful
    workflows: [ Create Ckan Base image ]
    types: [ completed ]
    workflow_dispatch:


jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::261730452028:role/OIDC_Github
          aws-region: eu-west-2
          role-session-name: CKANDockerDeployment

      - run: |
         docker context create ecs ckan-ecs --from-env
         docker context ls
