name: Dockerizing

on:
  workflow_run:
    workflows: [ Run Backend Tests, Test Frontend ]
    # only runs additional steps if [ tests ] was successful
    branches: [ "main" ]
    types: [ completed ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Validate prerequisites
        uses: ahmadnassri/action-workflow-run-wait@v1
        with:
          timeout: 900000 # we stop trying to check altogether after 15 mins
          delay: 300000 # we try to check the statuis of the presrequisite workflows after 5 mins after frontend testing ends
          
     
      
      - name: Testing triggers
        run: |
          echo "Unit and integration tests done "
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
