name: Docker Image CI

on:
  workflow_run:
    workflows: [ Run Backend Tests, Test Frontend ]
    # only runs additional steps if [ tests ] was successful
    branches: [ "main" ]
    types: [ completed ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1
      
      - name: Testing triggers
        run: |
          echo "Success"
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
